# Use an official Node.js image as the base image
FROM node:20 as builder

# Set the working directory in the container
WORKDIR /app

# Copy the rest of the application code to the working directory
COPY . .

# Install dependencies
RUN npm install

# Build the Angular application
RUN npm run build --prod

# Use a lightweight image for serving the application
FROM nginx:alpine

# Copy the build artifacts to the Nginx web server directory
COPY --from=builder /app/dist/altice-labs /usr/share/nginx/html